"""Price-action Research Memory seed: Nison / Brooks Contextual Setups.

Seeds Gaon's evidence-backed Research Memory (see `external_research_memory.py`
and `evidence_hypothesis.py`) with structured, evidence-backed hypotheses
derived from candlestick-analysis concepts commonly associated with Steve
Nison and price-action concepts commonly associated with Al Brooks.

This module does NOT invent a parallel knowledge store. Every hypothesis it
produces is generated by running the SAME real pipeline every other piece of
external research in this codebase uses: SourceProvenance -> a bounded
AutonomousKnowledgeResearchLoop (verbatim sentence-level claim extraction,
no LLM, no paraphrase) -> ExternalResearchMemoryStore -> the existing
EvidenceBackedHypothesisGenerator. This module supplies the domain content
and the market-scoping convention on top of that pipeline; it does not
reimplement any part of it.

Deliberately excluded, per explicit product requirement: a bare rule like
"Hammer = BUY" is never stored. Every hypothesis is a Contextual Setup - a
combination of market regime + structure + location + signal candle +
confirmation - never an isolated candle-pattern fact.

Market isolation: `PriceActionMarket` scopes every seeded hypothesis to
exactly one market via the topic_key namespace
("priceaction.<market>.<setup_id>"). Performance evidence for one market must
never be attached to, or presented as applying to, a hypothesis scoped to a
different market. This module only seeds BINANCE-scoped hypotheses (the four
already-implemented BIN-PA-01..04 research families in the sibling
binance_ai_bot_2 project are Contextual Setups in exactly this shape); the
same `build_contextual_setup`/seeding path works unchanged for a future KR
seed list under the "priceaction.kr.*" namespace.

Safety invariants (same as every module in this package):
- every hypothesis is PROPOSED (evidence-backed, unvalidated), never a
  validated/approved/tested claim
- no fabricated performance metric is stored (enforced by the existing
  _FORBIDDEN_PERFORMANCE_TOKENS check in evidence_hypothesis.py; this module
  never writes a percentage or a metric-shaped token into hypothesis text)
- no strategy mutation, Champion promotion, approval bypass, or trading
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
import hashlib
from typing import Mapping

from .conflicts import ClaimStance
from .autonomous_knowledge_loop import AutonomousKnowledgeResearchLoop, SourceEvidenceInput
from .evidence_hypothesis import (
    EvidenceBackedHypothesisGenerator,
    EvidenceBackedStrategyHypothesis,
    StrategyHypothesisStatus,
)
from .external_research_memory import (
    ExternalResearchMemoryStatus,
    ExternalResearchMemoryStore,
    external_research_memory_fingerprint,
)
from .provenance import SourceProvenance, SourceType, TrustLevel
from gaon.storage.foundation import GaonStorage


PRICE_ACTION_KNOWLEDGE_SCHEMA_VERSION = 1


class PriceActionMarket(str, Enum):
    BINANCE = "binance"
    KR = "kr"


@dataclass(frozen=True)
class PriceActionConcept:
    """A market-neutral candle/structure definition. Carries no performance
    evidence and is never, by itself, a tradable rule."""

    concept_id: str
    author: str  # "nison" | "brooks"
    definition: str

    def to_json(self) -> dict[str, object]:
        return {"concept_id": self.concept_id, "author": self.author, "definition": self.definition}


# Definitions below are original paraphrases of well-established, publicly
# documented technical-analysis concepts commonly associated with each
# author's published work. They are factual pattern/structure definitions,
# not performance claims, and carry no win rate, return, or sample-size
# figures of any kind.
NISON_CONCEPTS: tuple[PriceActionConcept, ...] = (
    PriceActionConcept("candlestick_context", "nison",
        "Candlestick analysis treats a single candle pattern as meaningful mainly in the context of the trend "
        "that precedes it, not in isolation from that trend."),
    PriceActionConcept("bullish_engulfing", "nison",
        "A bullish engulfing pattern is a two-candle reversal signal in which a bearish candle is followed by a "
        "larger bullish candle whose real body fully engulfs the prior candle's real body."),
    PriceActionConcept("bearish_engulfing", "nison",
        "A bearish engulfing pattern is a two-candle reversal signal in which a bullish candle is followed by a "
        "larger bearish candle whose real body fully engulfs the prior candle's real body."),
    PriceActionConcept("hammer", "nison",
        "A hammer is a single candle with a small real body near the top of its range and a lower shadow at "
        "least twice the body length, appearing after a decline and suggesting a possible bottom."),
    PriceActionConcept("shooting_star", "nison",
        "A shooting star is a single candle with a small real body near the bottom of its range and an upper "
        "shadow at least twice the body length, appearing after an advance and suggesting a possible top."),
    PriceActionConcept("morning_star", "nison",
        "A morning star is a three-candle bottoming pattern: a long bearish candle, a small-bodied candle that "
        "trades lower, and a bullish candle that closes well into the first candle's real body."),
    PriceActionConcept("evening_star", "nison",
        "An evening star is a three-candle topping pattern: a long bullish candle, a small-bodied candle that "
        "trades higher, and a bearish candle that closes well into the first candle's real body."),
    PriceActionConcept("piercing_pattern", "nison",
        "A piercing pattern is a two-candle bullish reversal in which a bearish candle is followed by a bullish "
        "candle that opens below the prior low and closes above the midpoint of the prior candle's real body."),
    PriceActionConcept("dark_cloud_cover", "nison",
        "A dark cloud cover is a two-candle bearish reversal in which a bullish candle is followed by a bearish "
        "candle that opens above the prior high and closes below the midpoint of the prior candle's real body."),
    PriceActionConcept("doji", "nison",
        "A doji is a candle whose open and close are nearly equal, signaling indecision between buyers and "
        "sellers rather than a directional bias by itself."),
    PriceActionConcept("confirmation", "nison",
        "A reversal candlestick pattern is treated as more reliable when confirmed by subsequent price action, "
        "such as a follow-through candle in the signaled direction, rather than acted on by itself."),
    PriceActionConcept("support_resistance", "nison",
        "Support and resistance are price areas where prior buying or selling pressure has previously reversed "
        "or paused price, and a candlestick signal occurring at such an area carries more weight."),
    PriceActionConcept("trend_context", "nison",
        "A candlestick pattern's implication depends on the prevailing trend it appears within, since the same "
        "pattern can imply different things during an uptrend, a downtrend, or a trading range."),
    PriceActionConcept("confluence", "nison",
        "Confluence is the alignment of a candlestick signal with an independent technical factor, such as a "
        "support or resistance level, which increases the credibility of the signal."),
)

BROOKS_CONCEPTS: tuple[PriceActionConcept, ...] = (
    PriceActionConcept("market_structure", "brooks",
        "Market structure is the alternation between trending phases and trading-range phases, and classifying "
        "the current structure is treated as a first step before reading any individual bar."),
    PriceActionConcept("trend_vs_trading_range", "brooks",
        "A trend is a series of higher highs and higher lows (or lower lows and lower highs) with strong "
        "directional bars, while a trading range is bounded, overlapping price action without sustained "
        "directional progress."),
    PriceActionConcept("signal_bar", "brooks",
        "A signal bar is the bar whose close, or a break beyond it, defines the entry trigger for a price "
        "action setup; its size and where it closes within its range convey the strength of the signal."),
    PriceActionConcept("high1_high2", "brooks",
        "In a downtrend, a High 1 is the first minor higher high after a decline, and a High 2 is a second, "
        "often more reliable, higher high used as a short-entry reference after the first attempt fails to hold."),
    PriceActionConcept("low1_low2", "brooks",
        "In an uptrend, a Low 1 is the first minor lower low after an advance, and a Low 2 is a second, often "
        "more reliable, lower low used as a long-entry reference after the first attempt fails to hold."),
    PriceActionConcept("second_entry", "brooks",
        "A second entry is a trade taken on the second attempt in a given direction after an initial attempt "
        "failed to follow through, which is treated as offering better odds than the first attempt."),
    PriceActionConcept("two_legged_pullback", "brooks",
        "A two-legged pullback is a correction against the trend made of two separate counter-trend legs "
        "separated by a small move back in the trend direction, after which trend resumption is considered "
        "more probable than after a single-leg pullback."),
    PriceActionConcept("breakout_pullback", "brooks",
        "A breakout pullback is a retracement back toward a recently broken support or resistance level, "
        "treated as a lower-risk entry in the direction of the original breakout if the level holds on the "
        "retest."),
    PriceActionConcept("failed_breakout", "brooks",
        "A failed breakout occurs when price breaks a prior swing high or low but quickly reverses back across "
        "it, which is treated as a tradable signal in the opposite direction from the failed break."),
    PriceActionConcept("trend_resumption", "brooks",
        "Trend resumption is price action re-establishing the prior trend direction after a pullback or a "
        "trading-range pause within that trend."),
    PriceActionConcept("bar_by_bar_context", "brooks",
        "Each bar is read in the context of the bars immediately preceding it, since the implication of any "
        "single bar depends on its position within the current trend or trading range."),
)

_ALL_CONCEPTS: dict[str, PriceActionConcept] = {
    concept.concept_id: concept for concept in (*NISON_CONCEPTS, *BROOKS_CONCEPTS)
}


@dataclass(frozen=True)
class ContextualSetupSpec:
    """One Contextual Setup: market regime + structure + location + signal
    candle + confirmation. This is the only shape a hypothesis may take in
    this module - never a bare "pattern implies direction" rule."""

    setup_id: str
    market: PriceActionMarket
    regime: str
    structure: str
    location: str
    signal_candle: str
    confirmation: str
    concept_ids: tuple[str, ...]
    bin_pa_family: str | None = None

    def __post_init__(self) -> None:
        for concept_id in self.concept_ids:
            if concept_id not in _ALL_CONCEPTS:
                raise ValueError(f"unknown price-action concept_id: {concept_id}")

    @property
    def topic_key(self) -> str:
        return f"priceaction.{self.market.value}.{self.setup_id}"

    def description_sentences(self) -> tuple[str, ...]:
        """Verbatim-extractable sentences describing this setup. Every
        sentence is source text handed to the real claim extractor - not a
        performance claim, and it contains no percentage or metric token."""
        sentences = [
            f"Contextual Setup {self.setup_id}: within a {self.regime}, this setup requires {self.structure}.",
            f"The setup looks for this structure at {self.location}.",
            f"The signal candle for this setup is {self.signal_candle}.",
            f"Confirmation for this setup is {self.confirmation}.",
        ]
        for concept_id in self.concept_ids:
            sentences.append(_ALL_CONCEPTS[concept_id].definition)
        return tuple(sentences)

    def to_json(self) -> dict[str, object]:
        return {
            "setup_id": self.setup_id,
            "market": self.market.value,
            "topic_key": self.topic_key,
            "regime": self.regime,
            "structure": self.structure,
            "location": self.location,
            "signal_candle": self.signal_candle,
            "confirmation": self.confirmation,
            "concept_ids": list(self.concept_ids),
            "bin_pa_family": self.bin_pa_family,
        }


def build_contextual_setup(
    *,
    setup_id: str,
    market: PriceActionMarket,
    regime: str,
    structure: str,
    location: str,
    signal_candle: str,
    confirmation: str,
    concept_ids: tuple[str, ...],
    bin_pa_family: str | None = None,
) -> ContextualSetupSpec:
    """Reusable combinator: mints ONE new Contextual Setup from a
    regime/structure/location/signal/confirmation permutation drawn from the
    NISON_CONCEPTS/BROOKS_CONCEPTS catalog.

    This is the actual "Strategy Hypothesis Generator" input surface: any
    caller (a human, or a future Gaon research-director combinatorial
    expansion step) can call this with a NEW permutation not present in
    BINANCE_CONTEXTUAL_SETUPS below, then pass the result through
    seed_price_action_hypothesis() to mint a real, evidence-backed,
    PROPOSED hypothesis via the existing EvidenceBackedHypothesisGenerator -
    the seed list below is a starting set, not the ceiling of what this
    surface can produce.
    """
    return ContextualSetupSpec(
        setup_id=setup_id, market=market, regime=regime, structure=structure, location=location,
        signal_candle=signal_candle, confirmation=confirmation, concept_ids=concept_ids,
        bin_pa_family=bin_pa_family,
    )


# Seed Contextual Setups for the Binance market. Four are direct conceptual
# analogues of the already-implemented BIN-PA-01..04 research families in
# binance_ai_bot_2/price_action_strategy.py (contextual candlestick,
# Brooks-style second entry, two-leg pullback + confirmation,
# breakout-pullback/failed-breakout) so a human can trace "Gaon hypothesis X"
# to "BIN-PA family Y". The last two are a genuinely NEW combination (a
# trading-range setup) that no current BIN-PA family implements, proving
# build_contextual_setup() can generate hypotheses beyond direct 1:1 mirrors
# of existing code.
BINANCE_CONTEXTUAL_SETUPS: tuple[ContextualSetupSpec, ...] = (
    build_contextual_setup(
        setup_id="bull_context_candle_confirmation",
        market=PriceActionMarket.BINANCE,
        regime="1H bullish trend context (fast EMA above slow EMA with a rising slope)",
        structure="a Nison-style contextual candlestick confirmation occurring within that trend, with no "
                   "additional pullback structure required",
        location="the current 5m close, wherever it falls within the 1H trend (no explicit support/resistance "
                  "location constraint)",
        signal_candle="a bullish engulfing pattern, a hammer, or a strong bullish bar",
        confirmation="the signal candle's own close in the trend direction; no separate follow-through bar is "
                     "required",
        concept_ids=("trend_context", "bullish_engulfing", "hammer", "confirmation"),
        bin_pa_family="BIN-PA-01",
    ),
    build_contextual_setup(
        setup_id="bull_second_entry_pullback",
        market=PriceActionMarket.BINANCE,
        regime="1H bullish trend context",
        structure="a Brooks-style second entry: at least two distinct down-legs (a two-legged pullback) against "
                   "the 1H uptrend, observed on the 5m chart",
        location="the low reached after the second down-leg of the pullback",
        signal_candle="a strong bullish signal bar closing near its high",
        confirmation="the signal bar's own close serves as the entry trigger, consistent with a second-entry "
                     "setup",
        concept_ids=("trend_vs_trading_range", "signal_bar", "second_entry", "two_legged_pullback", "low1_low2"),
        bin_pa_family="BIN-PA-02",
    ),
    build_contextual_setup(
        setup_id="bull_two_leg_pullback_confirmed",
        market=PriceActionMarket.BINANCE,
        regime="1H bullish trend context",
        structure="a two-legged pullback combined with a Nison-style candlestick confirmation pattern, rather "
                   "than either condition alone",
        location="the support area reached after the second down-leg of the pullback",
        signal_candle="a bullish engulfing pattern, a hammer, or a strong bullish bar",
        confirmation="the candlestick confirmation pattern must coincide with the completed two-legged pullback "
                     "before entry is considered",
        concept_ids=("two_legged_pullback", "support_resistance", "bullish_engulfing", "confirmation", "confluence"),
        bin_pa_family="BIN-PA-03",
    ),
    build_contextual_setup(
        setup_id="bear_two_leg_pullback_confirmed",
        market=PriceActionMarket.BINANCE,
        regime="1H bearish trend context",
        structure="a two-legged pullback (two up-legs) combined with a Nison-style bearish candlestick "
                   "confirmation pattern",
        location="the resistance area reached after the second up-leg of the pullback",
        signal_candle="a bearish engulfing pattern, a shooting star, or a strong bearish bar",
        confirmation="the bearish candlestick confirmation pattern must coincide with the completed two-legged "
                     "pullback before entry is considered",
        concept_ids=("two_legged_pullback", "support_resistance", "bearish_engulfing", "confirmation", "confluence"),
        bin_pa_family="BIN-PA-03",
    ),
    build_contextual_setup(
        setup_id="bull_breakout_pullback_or_failed_breakout",
        market=PriceActionMarket.BINANCE,
        regime="1H bullish trend context",
        structure="a breakout-pullback or a failed-breakout structure relative to a recent swing boundary",
        location="a retest of a previously broken resistance boundary, now acting as support",
        signal_candle="a bullish engulfing pattern, a hammer, or a strong bullish bar",
        confirmation="a close back above the retested boundary on the signal bar, consistent with trend "
                     "resumption",
        concept_ids=("breakout_pullback", "failed_breakout", "trend_resumption", "bullish_engulfing", "confirmation"),
        bin_pa_family="BIN-PA-04",
    ),
    build_contextual_setup(
        setup_id="range_support_doji_piercing_reversal",
        market=PriceActionMarket.BINANCE,
        regime="1H trading-range context (no established higher-high/higher-low or lower-high/lower-low trend)",
        structure="price reaching the edge of an established trading range, read bar-by-bar rather than assumed "
                   "to be trending",
        location="the support boundary of the trading range",
        signal_candle="a doji at the range support, followed by a piercing pattern",
        confirmation="the piercing candle's close above the midpoint of the doji's preceding bar, followed by a "
                     "next bar that continues higher",
        concept_ids=("market_structure", "trend_vs_trading_range", "doji", "piercing_pattern", "bar_by_bar_context",
                     "support_resistance"),
        bin_pa_family=None,
    ),
    build_contextual_setup(
        setup_id="range_resistance_doji_darkcloud_reversal",
        market=PriceActionMarket.BINANCE,
        regime="1H trading-range context (no established higher-high/higher-low or lower-high/lower-low trend)",
        structure="price reaching the edge of an established trading range, read bar-by-bar rather than assumed "
                   "to be trending",
        location="the resistance boundary of the trading range",
        signal_candle="a doji at the range resistance, followed by a dark cloud cover",
        confirmation="the dark cloud candle's close below the midpoint of the doji's preceding bar, followed by "
                     "a next bar that continues lower",
        concept_ids=("market_structure", "trend_vs_trading_range", "doji", "dark_cloud_cover", "bar_by_bar_context",
                     "support_resistance"),
        bin_pa_family=None,
    ),
)


def _book_source(*, title: str, locator: str, text: str, author: str) -> SourceProvenance:
    return SourceProvenance.create(
        source_type=SourceType.BOOK,
        title=title,
        locator=locator,
        content_sha256=hashlib.sha256(text.encode("utf-8")).hexdigest(),
        trust_level=TrustLevel.HIGH,
        author=author,
        publisher="price-action-knowledge-seed",
        published_at="1991-01-01" if author == "Steve Nison" else "2009-01-01",
        license_name="research-reference-only",
        ingested_at="2026-08-23T00:00:00+00:00",
    )


def seed_price_action_hypothesis(
    setup: ContextualSetupSpec,
    *,
    storage: GaonStorage,
) -> EvidenceBackedStrategyHypothesis:
    """Runs ONE Contextual Setup through the real pipeline: SourceProvenance
    -> AutonomousKnowledgeResearchLoop (verbatim claim extraction) ->
    ExternalResearchMemoryStore (persisted, deduplicated) ->
    EvidenceBackedHypothesisGenerator. Returns the resulting PROPOSED
    hypothesis. Raises if the pipeline blocks at any stage (e.g. a
    fabricated-metric token slipped into a setup's text) - a silent
    fallback here would risk seeding knowledge that only looks
    evidence-backed."""
    author = "Al Brooks" if any(_ALL_CONCEPTS[cid].author == "brooks" for cid in setup.concept_ids) else "Steve Nison"
    content_text = " ".join(setup.description_sentences())
    source = _book_source(
        title=f"Contextual Setup seed: {setup.setup_id}",
        locator=f"https://example.invalid/price-action-knowledge-seed/{setup.topic_key}",
        text=content_text,
        author=author,
    )
    loop = AutonomousKnowledgeResearchLoop().run(
        topic_key=setup.topic_key,
        evidence=(SourceEvidenceInput(source, content_text.encode("utf-8"), "text/plain", ClaimStance.SUPPORTS),),
    )

    store = ExternalResearchMemoryStore(storage)
    write_result = store.add_loop_result(loop, created_at="2026-08-23T00:00:00+00:00")
    if write_result.status not in (ExternalResearchMemoryStatus.STORED, ExternalResearchMemoryStatus.DUPLICATE):
        raise RuntimeError(
            f"price-action knowledge seed blocked for {setup.topic_key}: {write_result.blockers}"
        )
    record = write_result.record or store.find_by_fingerprint(external_research_memory_fingerprint(loop))

    generator = EvidenceBackedHypothesisGenerator()
    hypothesis = generator.generate(
        topic_key=setup.topic_key,
        memories=(record,),
        changed_rules=(
            f"Enter only when {setup.structure}, at {setup.location}, confirmed by {setup.signal_candle}, with "
            f"{setup.confirmation}.",
        ),
        rationale=(
            f"This Contextual Setup combines a {setup.regime} with {setup.structure} at {setup.location}, "
            "rather than treating the signal candle as meaningful on its own."
        ),
        mechanism=(
            f"Entry only triggers once the signal candle ({setup.signal_candle}) appears and {setup.confirmation}; "
            "the surrounding regime and structure are prerequisites, not optional context."
        ),
        falsification_criteria=(
            "Reject this hypothesis if independent out-of-sample research evidence does not show the combined "
            "setup outperforming the signal candle alone, evaluated separately per market.",
        ),
    )
    if hypothesis.status is not StrategyHypothesisStatus.PROPOSED:
        raise RuntimeError(f"price-action hypothesis for {setup.topic_key} was blocked: {hypothesis.blockers}")
    return hypothesis


def seed_binance_price_action_hypotheses(
    *,
    storage: GaonStorage,
) -> tuple[EvidenceBackedStrategyHypothesis, ...]:
    """Seeds every BINANCE_CONTEXTUAL_SETUPS entry as a real, evidence-backed
    PROPOSED hypothesis. Never touches a KR-scoped topic_key."""
    hypotheses = []
    for setup in BINANCE_CONTEXTUAL_SETUPS:
        assert setup.market is PriceActionMarket.BINANCE, "this seed function is BINANCE-only by construction"
        hypotheses.append(seed_price_action_hypothesis(setup, storage=storage))
    return tuple(hypotheses)


def production_price_action_knowledge_seed_release_check() -> Mapping[str, object]:
    """Regression guard: seeding produces one PROPOSED, evidence-backed
    hypothesis per Binance Contextual Setup, none carry a fabricated
    performance metric, all are correctly market-namespaced, at least one
    setup is a genuinely new combination not mapped to any existing BIN-PA
    family, and no promotion/order/mutation invariant is touched."""
    import tempfile

    with tempfile.TemporaryDirectory() as tmp:
        storage = GaonStorage(tmp)
        hypotheses = seed_binance_price_action_hypotheses(storage=storage)

    all_proposed = all(h.status is StrategyHypothesisStatus.PROPOSED for h in hypotheses)
    all_binance_scoped = all(h.topic_key.startswith("priceaction.binance.") for h in hypotheses)
    no_kr_topic = all("priceaction.kr." not in h.topic_key for h in hypotheses)
    all_evidence_linked = all(len(h.claim_ids) > 0 and len(h.evidence_memory_ids) > 0 for h in hypotheses)
    none_tested_or_validated = all(
        not h.tested and not h.knowledge_validated and not h.production_approved and not h.policy_applied
        for h in hypotheses
    )
    none_mutate_or_trade = all(not h.strategy_mutated and not h.order_executed for h in hypotheses)
    covers_nison_and_brooks_families = (
        any(s.bin_pa_family == "BIN-PA-01" for s in BINANCE_CONTEXTUAL_SETUPS)
        and any(s.bin_pa_family == "BIN-PA-02" for s in BINANCE_CONTEXTUAL_SETUPS)
        and any(s.bin_pa_family == "BIN-PA-03" for s in BINANCE_CONTEXTUAL_SETUPS)
        and any(s.bin_pa_family == "BIN-PA-04" for s in BINANCE_CONTEXTUAL_SETUPS)
    )
    has_novel_combination = any(s.bin_pa_family is None for s in BINANCE_CONTEXTUAL_SETUPS)
    unique_hypothesis_ids = len({h.hypothesis_id for h in hypotheses}) == len(hypotheses)

    checks = {
        "seeded_all_setups": len(hypotheses) == len(BINANCE_CONTEXTUAL_SETUPS),
        "all_proposed": all_proposed,
        "all_binance_scoped": all_binance_scoped,
        "no_kr_topic_present": no_kr_topic,
        "all_evidence_linked": all_evidence_linked,
        "none_tested_or_validated": none_tested_or_validated,
        "none_mutate_or_trade": none_mutate_or_trade,
        "covers_all_four_bin_pa_families": covers_nison_and_brooks_families,
        "has_novel_non_bin_pa_combination": has_novel_combination,
        "unique_hypothesis_ids": unique_hypothesis_ids,
    }
    if not all(checks.values()):
        failed = ",".join(name for name, ok in checks.items() if not ok)
        raise RuntimeError(f"price-action knowledge seed release check failed: {failed}")

    return {
        "schema_version": PRICE_ACTION_KNOWLEDGE_SCHEMA_VERSION,
        **checks,
        "seeded_count": len(hypotheses),
        "strategy_mutated": False,
        "order_executed": False,
        "champion_promoted": False,
        "approval_bypassed": False,
        "safety": "pass",
    }
